services:
  db:
    image: postgres:16-alpine
    container_name: board-db
    environment:
      POSTGRES_DB: board
      POSTGRES_USER: board
      POSTGRES_PASSWORD: board
    ports:
      - "5432:5432"
    volumes:
      - board-db-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  board-db-data:
