spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/board}
    username: ${DB_USERNAME:board}
    password: ${DB_PASSWORD:board}
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true