spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    # 이름과 비밀번호를 환경에 맞게 설정
    username:
    password:
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true